apiVersion: apps/v1
kind: Deployment
metadata:
  name: bincalc-deploy
  labels:
    app: bincalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bincalc
  template:
    metadata:
      labels:
        app: bincalc
    spec:
      containers:
      - name: bincalc-container
        image: us-central1-docker.pkg.dev/project-68ef26d0-4bfe-45e1-9eb/binary-calc/binarycalculator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_ADDRESS
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"