apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - name: binarycalculator
          image: us-central1-docker.pkg.dev/project-ff93592e-5066-4eb2-a1e/sofe3980u/binarycalculator:latest
          ports:
            - containerPort: 8080
